language: csharp
solution: X12.sln
mono: none
dotnet: 2.1.4
env:
  - PACKAGE_VERSION="5.0.*"
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test ./tests/X12.Core.Tests.Unit/bin/Release/netcoreapp2.0/X12.Core.Tests.Unit.dll
  
