language: csharp
solution: X12.sln
mono: none
dotnet: 2.1.4
env:
  - PACKAGE_VERSION="5.0.*"
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test ./tests/X12.Core.Hipaa.Tests.Unit/X12.Core.Hipaa.Tests.Unit.csproj
  - dotnet test ./tests/X12.Core.Tests.Integration/X12.Core.Tests.Integration.csproj
  - dotnet test ./tests/X12.Core.Tests.Unit/X12.Core.Tests.Unit.csproj
  - dotnet test ./tests/X12.Core.Validation.Tests.Unit/X12.Core.Validation.Tests.Unit.csproj
